name: master-cd

on:
  push:
    branches: [ main ]
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Run install
        run: yarn

      - name: Build
        run: CI=false yarn build


      - name: Upload bundle
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_PRD_HOST }}
          username: ${{ secrets.SSH_PRD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./build"
          target: "/opt/test"

